Add mltrace assert exceptions & logging trigger results
loglabs/mltrace pull request #273
Opened 2021-11-28 19:41 UTC by aditim1359

2021-11-30 03:49 UTC, shreyashankar requested changes
Small nits

2021-11-30 03:49 UTC, shreyashankar commented on examples/new_framework_test.py
> +# c = Component("aditi", "test", "test_description")
Delete line

2021-11-30 03:49 UTC, shreyashankar commented on mltrace/client.py
> +    print("test results from cr: ", cr.test_results)
remove print stmt

2021-11-30 03:49 UTC, shreyashankar commented on mltrace/db/store.py
> +        print("before store: ", component_run.test_results)
remove print stmt

2021-11-30 03:49 UTC, shreyashankar commented on mltrace/entities/base_component.py
> +                print("status ", status)
remove print

2021-11-30 03:49 UTC, shreyashankar commented on mltrace/entities/tests.py
> +functions to be run within each test.
Move this file to examples/

2021-11-30 03:49 UTC, shreyashankar commented on mltrace/entities/components.py
> +This file defines different kinds of components and the
Move this file to examples/

2021-11-30 18:47 UTC, aditim1359 commented on mltrace/entities/components.py
> +This file defines different kinds of components and the
done

2021-11-30 18:47 UTC, aditim1359 commented on examples/new_framework_test.py
> +# c = Component("aditi", "test", "test_description")
done

2021-11-30 18:47 UTC, aditim1359 commented on mltrace/client.py
> +    print("test results from cr: ", cr.test_results)
done

2021-11-30 18:47 UTC, aditim1359 commented on mltrace/db/store.py
> +        print("before store: ", component_run.test_results)
done

2021-11-30 18:47 UTC, aditim1359 commented on mltrace/entities/base_component.py
> +                print("status ", status)
done

2021-12-01 19:10 UTC, shreyashankar approved these changes
Merge after changing the revision numbers

2021-12-01 19:10 UTC, shreyashankar commented on mltrace/db/migrations/versions/b86f884647fe_add_test_result_column_to_component_runs.py
> +down_revision = '331edc89f24b'
change this down_revision to "8824d15c21d6" (just tested on my computer)

2021-12-01 19:10 UTC, shreyashankar commented on mltrace/db/migrations/versions/b86f884647fe_add_test_result_column_to_component_runs.py
> +Revises: 331edc89f24b
change the down revision to "8824d15c21d6"

2021-12-03 00:57 UTC, merged